name: fb_todo
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.12.0
  firebase_auth: ^0.14.0
  google_sign_in: any
  provider: ^3.1.0
  flutter_auth_buttons: ^0.5.0
dependency_overrides:
  crossfire:
    path: /Users/ryjohn/code/github/apptreesoftware/crossfire/crossfire
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
